# Artificial Neural Network

### Importing the libraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.3.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [21]:
dataset = pd.read_csv('TeamData.csv')
X = dataset.iloc[:822, 3:9].values
y = dataset.iloc[:822, -1].values

In [22]:
print(X)

[[1.62e+02 8.13e+02 7.43e+02 3.23e-01 4.34e-01 2.52e-01]
 [1.62e+02 8.55e+02 7.43e+02 3.36e-01 4.52e-01 2.58e-01]
 [1.62e+02 7.29e+02 9.81e+02 3.10e-01 4.15e-01 2.46e-01]
 ...
 [1.62e+02 5.99e+02 6.98e+02 3.20e-01 3.58e-01 2.56e-01]
 [1.62e+02 6.76e+02 6.96e+02 3.31e-01 3.76e-01 2.59e-01]
 [1.62e+02 7.67e+02 6.61e+02 3.28e-01 4.19e-01 2.65e-01]]


In [23]:
print(y)

[0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 1 1 0 0 0 0 0 1 1 0 0 1 0 1 0 1 1 0 0
 1 1 0 1 0 0 1 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 1 1 0 1 0 0 1
 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0
 0 0 0 1 0 0 1 1 1 0 0 0 0 1 0 0 0 0 0 1 1 0 1 0 0 0 1 1 0 0 1 0 0 0 1 0 1
 1 0 0 0 1 0 0 0 0 0 0 1 0 1 1 1 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 1 0 1 0 1 0
 0 1 1 0 1 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 0 1 0 0
 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 1 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1
 0 1 0 0 0 0 1 1 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 1 0
 1 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 1 0 1 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0
 1 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 1 1 0
 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1
 1 1 1 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 1 0
 0 1 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 1 0 1 1 0 0 0 0 0 1 0 

### Encoding categorical data

Label Encoding the "Gender" column

### Splitting the dataset into the Training set and Test set

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [26]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [27]:
ann.add(tf.keras.layers.Dense(units=7, activation='relu'))

### Adding the second hidden layer

In [28]:
ann.add(tf.keras.layers.Dense(units=7, activation='relu'))

### Adding the output layer

In [29]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

### Training the ANN on the Training set

In [30]:
ann.optimizer.learning_rate = 0.01

AttributeError: 'NoneType' object has no attribute 'learning_rate'

In [34]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [35]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
21/21 [==============================] - 0s 746us/step - loss: 0.7225 - accuracy: 0.5266
Epoch 2/100
21/21 [==============================] - 0s 768us/step - loss: 0.6840 - accuracy: 0.7002
Epoch 3/100
21/21 [==============================] - 0s 851us/step - loss: 0.6504 - accuracy: 0.7960
Epoch 4/100
21/21 [==============================] - 0s 986us/step - loss: 0.6137 - accuracy: 0.8128
Epoch 5/100
21/21 [==============================] - 0s 905us/step - loss: 0.5752 - accuracy: 0.8128
Epoch 6/100
21/21 [==============================] - 0s 665us/step - loss: 0.5349 - accuracy: 0.8189
Epoch 7/100
21/21 [==============================] - 0s 905us/step - loss: 0.4955 - accuracy: 0.8158
Epoch 8/100
21/21 [==============================] - 0s 921us/step - loss: 0.4625 - accuracy: 0.8265
Epoch 9/100
21/21 [==============================] - 0s 841us/step - loss: 0.4344 - accuracy: 0.8371
Epoch 10/100
21/21 [==============================] - 0s 915us/step - loss: 0.4113 - accura

21/21 [==============================] - 0s 612us/step - loss: 0.2456 - accuracy: 0.8935
Epoch 82/100
21/21 [==============================] - 0s 734us/step - loss: 0.2451 - accuracy: 0.8919
Epoch 83/100
21/21 [==============================] - 0s 605us/step - loss: 0.2455 - accuracy: 0.8904
Epoch 84/100
21/21 [==============================] - 0s 725us/step - loss: 0.2450 - accuracy: 0.8935
Epoch 85/100
21/21 [==============================] - 0s 818us/step - loss: 0.2448 - accuracy: 0.8889
Epoch 86/100
21/21 [==============================] - 0s 662us/step - loss: 0.2446 - accuracy: 0.8874
Epoch 87/100
21/21 [==============================] - 0s 689us/step - loss: 0.2445 - accuracy: 0.8919
Epoch 88/100
21/21 [==============================] - 0s 704us/step - loss: 0.2446 - accuracy: 0.8935
Epoch 89/100
21/21 [==============================] - 0s 703us/step - loss: 0.2444 - accuracy: 0.8935
Epoch 90/100
21/21 [==============================] - 0s 748us/step - loss: 0.2442 - accuracy: 

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [36]:
print(ann.predict(sc.transform([[162, 712, 604, .332, .453, .259]])))

[[0.94210565]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [37]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]

### Making the Confusion Matrix

In [38]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[109   8]
 [  9  39]]


0.896969696969697

NameError: name 'kwargs' is not defined